
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 29 23:46:30 CST 2017
//----------------------------------------------------

package proyecto_compiladores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 19;
  public static final int CHAR = 37;
  public static final int COMMENT = 40;
  public static final int SEMI = 20;
  public static final int INT = 36;
  public static final int ARRAY = 3;
  public static final int LESS = 28;
  public static final int MINUS = 18;
  public static final int NOT = 8;
  public static final int AND = 2;
  public static final int TYPE = 14;
  public static final int OR = 10;
  public static final int COMMA = 21;
  public static final int BEGIN = 4;
  public static final int PLUS = 17;
  public static final int IF = 7;
  public static final int DOT = 34;
  public static final int RT_CB = 39;
  public static final int OF = 9;
  public static final int EOF = 0;
  public static final int GTR = 27;
  public static final int error = 1;
  public static final int PROGRAM = 11;
  public static final int LEFT_BRKT = 24;
  public static final int LEFT_CB = 38;
  public static final int IDENT = 35;
  public static final int RT_PAREN = 23;
  public static final int EQ = 26;
  public static final int ASSMNT = 33;
  public static final int TIMES = 16;
  public static final int COLON = 32;
  public static final int ELSE = 5;
  public static final int NOT_EQ = 31;
  public static final int WHILE = 42;
  public static final int LESS_EQ = 29;
  public static final int RT_BRKT = 25;
  public static final int THEN = 13;
  public static final int END = 6;
  public static final int LEFT_PAREN = 22;
  public static final int GTR_EQ = 30;
  public static final int VAR = 15;
  public static final int PROCEDURE = 12;
  public static final int DO = 41;
}

